function Set-AzureFunctionStatus
{
<#
	.SYNOPSIS
		Sets the return status of the function.
	
	.DESCRIPTION
		Sets the return status of the function.
		By default, the status is "OK"
	
	.PARAMETER Status
		Set the HTTP status for the return from Azure Functions.
		Any status other than OK will cause a terminating error if run outside of Azure Functions.
	
	.EXAMPLE
		PS C:\> Set-AzureFunctionStatus -Status BadRequest
	
		Updates the status to say "BadRequest"
#>
	[CmdletBinding()]
	param (
		[Parameter(Mandatory = $true)]
		[System.Net.HttpStatusCode]
		$Status
	)
	
	Set-PSFConfig -FullName 'AutogeneratedAzureFunction.Function.StatusCode' -Value $Status
}